[DO NOT MERGE] Refactor versioning
wantedly/apig pull request #113
Opened 2016-09-29 04:12 UTC by shimastripe

After #112 , merge this PR.

## WHAT
- Use the structure for versioning

2016-10-03 10:54 UTC, dtan4 commented
plz rebase this branch to the latest master.

2016-10-03 10:55 UTC, shimastripe commented
Rebase this branch to the latest master! Plz check.

2016-10-03 10:59 UTC, dtan4 requested changes

2016-10-03 10:59 UTC, dtan4 commented on _templates/skeleton/version/version.go.tmpl
> +func (self *Version) initialize(c *gin.Context) error {
This method should extract out of `Version` structure, or include in `NewVersion` method.

2016-10-03 12:41 UTC, shimastripe commented on _templates/skeleton/version/version.go.tmpl
> +func (self *Version) initialize(c *gin.Context) error {
OK, I fixed.

2016-10-04 00:44 UTC, dtan4 requested changes

2016-10-04 00:44 UTC, dtan4 commented on _templates/skeleton/version/version.go.tmpl
> +func (self Version) Range(op string, right string) bool {
Change receiver type as pointer.

`func (v *Version) Range(op string, right string) bool`

2019-11-12 04:00 UTC, closed without merging